version: '3'
services:
    mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: hello
            MYSQL_DATABASE: sample_db
            MYSQL_USER: myuser
            MYSQL_PASSWORD: "1234"
        ports:
            - 3306:3306
        network_mode: bridge
        volumes:
            - "../.volumes/mysql/datadir:/var/lib/mysql"
            - "../mysql/sample_data:/docker-entrypoint-initdb.d"